### ISSUE TITLE
Low TPS when dynmap-structures is enabled

### ISSUE THREAD

**Issue by FrederikTheDane** [KovuTheHusky/dynmap-structures#14]
## Expected Behavior
TPS is normally above 19 when the plugin is not installed, and should still be acceptable when dynmap-structures is installed

## Actual Behavior
The TPS on my server drops to around 16-17, which causes frustration amongst my users and myself, as the server lags. I've been disconnected multiple times from the server with the standard "Timed out" message. Removing the plugin fixes this. 

## Steps to Reproduce the Problem

  1. Install dynmap and dynmap-structures
  2. Check the TPS on the server with /tps

## Specifications

I do not know the full specs of my server, as it is hosted on cubedhost.com

  - dynmap-structures: 2.0.0
  - dynmap: 3.0-beta-3
  - Bukkit/Spigot: Spigot version \#2074 (git-Spigot-b0f4c22-2ced023) Minecraft 1.13.2
  - Java: 1.8.0_131
  - System: Some linux distro, I assume

**Comment by KovuTheHusky** [comment]
This issue was introduced during the rewrite for 1.13 and I've already been working on alternatives. Expect a release soon.

**Comment by KovuTheHusky** [comment]
This issue was introduced during the 1.13

**Comment by KovuTheHusky** [comment]
I'll have a new version later today, I would have finished it tonight but I should really sleep since I've been sick the past few days.

**Comment by FrederikTheDane** [comment]
Amazing! Thanks for the fast response 😄

**Comment by KovuTheHusky** [comment]
Should be fixed, most of the code changes are in 21e267a20beb5d79c568191e12d7e9a03dd64e39. If you wouldn't mind, give the [new release](https://github.com/KovuTheHusky/dynmap-structures/releases/tag/2.1.0) a quick test and let me know if you get better performance before I publish it to the CraftBukkit and Spigot websites.

**Comment by FrederikTheDane** [comment]
Just tried it, TPS is still bad sadly :(

**Comment by FrederikTheDane** [comment]
I assume you mean the markers.yml in the dynmap folder?
Config (Just default): https://pastebin.com/VjKNiQcY
Markers: https://pastebin.com/nriUcR2B

**Comment by KovuTheHusky** [comment]
Okay, I think my hashmaps are slowing things down. Let me see what I can do.

**Comment by KovuTheHusky** [comment]
Alright, [this release](https://github.com/KovuTheHusky/dynmap-structures/releases/tag/2.1.1) is my last attempt without rethinking and rewriting a whole bunch of stuff. Give it a shot and let me know how it performs. I'll be running it on my server as well for the next day or so to see how it is.

**Comment by FrederikTheDane** [comment]
That seems to have done the trick. TPS is now 19-20 Thanks a ton!

**Comment by KovuTheHusky** [comment]
Wonderful! I'll push that release to CraftBukkit/Spigot when I get a chance.
