### ISSUE TITLE
Random crashes on chunk load

### ISSUE THREAD

**Issue by TheSoulrester** [KovuTheHusky/dynmap-structures#17]
I think this plugin is not compatible with the latest craftbook version for 1.14.2

this is the error i got:
https://hastebin.com/dixosizaka.rb

**Comment by KovuTheHusky** [comment]
Unrelated to craftbook, but looking into it.

**Comment by TheSoulrester** [comment]
did you see the error log? i think hastebin deleted it before you was able to read it :(

**Comment by TheSoulrester** [comment]
here is a pastebin link: https://pastebin.com/5dB44LhA

**Comment by KovuTheHusky** [comment]
I was able to replicate the crash without Craftbook. It's actually just dynmap-structures and Minecraft itself causing the issue. The real issue is a ConcurrentModificationException happening on chunk load involving my plugin as well as Minecraft's code.

**Comment by KovuTheHusky** [comment]
Do me a favor and try this version? I need to zip it because GitHub doesn't allow jar uploads.

[dynmap-structures-2.2.1-SNAPSHOT.jar.zip](https://github.com/KovuTheHusky/dynmap-structures/files/3303684/dynmap-structures-2.2.1-SNAPSHOT.jar.zip)

**Comment by TheSoulrester** [comment]
> I was able to replicate the crash without Craftbook. It's actually just dynmap-structures and Minecraft itself causing the issue. The real issue is a ConcurrentModificationException happening on chunk load involving my plugin as well as Minecraft's code.

oh really? i thought this was based on craftbook because after i created the sign "Chunk" for having a chunkloader, the server crashed. and moreover, in the log it was called "chunkload" - so i thought this was caused by craftbook.



> Do me a favor and try [this version](https://github.com/KovuTheHusky/dynmap-structures/files/3303684/dynmap-structures-2.2.1-SNAPSHOT.jar.zip)? I need to zip it because GitHub doesn't allow jar uploads.

i will test it as soon as i can :)

**Comment by KovuTheHusky** [comment]
Still figuring out the best way to deal with this. Right now I'm spinning each locate out into its own thread to avoid the ConcurrentModificationExceptions but NMS is still spitting out NullPointerExceptions when locateNearestStructure() is called. And nothing I'm using can be null so it's an unhandled exception in Spigot, CB, or NMS itself.

**Comment by KovuTheHusky** [comment]
Give [this version](https://github.com/KovuTheHusky/dynmap-structures/files/3317925/dynmap-structures-2.2.1-SNAPSHOT.jar.zip) a try. I may need to open an issue with something up the stack (Minecraft, Spigot, etc) for a real fix though.

**Comment by PowerYuppie** [comment]
> Give [this version](https://github.com/KovuTheHusky/dynmap-structures/files/3317925/dynmap-structures-2.2.1-SNAPSHOT.jar.zip) a try. I may need to open an issue with something up the stack (Minecraft, Spigot, etc) for a real fix though.

This seems to be working.
Side-question: Do you need to travel around for this plugin to pick up all the structures, or can you rely on a dynmap render to do that? Because as of now, the plugin seem stable but I only see structures that I've "discovered" since installing it.

**Comment by KovuTheHusky** [comment]
The way it works now (since the changes I was forced to make in 1.13) is on chunk load.

**Comment by KovuTheHusky** [comment]
Should be closed by 58d7c44ad1800b77bfa0ff54088fbe823eabad96 and e9a033e129cf2f70ab3818dea7056f28b857b1fb.
