### ISSUE TITLE
Add toggle for warnings

### ISSUE THREAD

**Issue by TheSoulrester** [KovuTheHusky/dynmap-structures#20]
My console's getting dumped.... :(

this is an excerpt from the console: https://pastebin.com/wWtDct3j

**Comment by KovuTheHusky** [comment]
I will add a toggle in the next version. I actually wanted to see how many people would report this. This is the "fix" for the crashing issue. That null pointer is thrown from Minecraft's code itself. I'm hoping that code is cleaned up by Mojang or patched by Spigot or Paper. Maybe once 1.14.x is stable.

**Comment by KovuTheHusky** [comment]
A question for yourself and any others that come here: how often are you seeing these warnings and what is happening when they appear? (Are people online? Discovering new chunks? Logging in or out?)

**Comment by KovuTheHusky** [comment]
Have you been receiving these warnings recently? has 1.14.3 improved the situation at all?

**Comment by TheSoulrester** [comment]
there weren't any errors now in the console, but many heavy server performance issues. 
i disabled it now again.

**Comment by KovuTheHusky** [comment]
I will work on #24 when I get some free time to improve performance.
