### ISSUE TITLE
Label Coordinates are way off

### ISSUE THREAD

**Issue by omega9380** [KovuTheHusky/dynmap-structures#22]
**Describe the bug**
I have enabled "inc-coord" in dynmap-structures to include coordinates with the marker label.  The markers are showing physically in their correct locations, however the labels are off by a considerable margin

**To Reproduce**
Set "inc-coord" in config.yaml to "true"
Log into server and look at the coordinate labels

**Expected behavior**
Coordinate labels to match physical coordinates of the markers

**Screenshots**
![image](https://user-images.githubusercontent.com/13081643/62815909-7ab1d100-baed-11e9-94b5-e52e9184ec70.png)

**Desktop (please complete the following information):**
 - OS: Hosted server on CubedHost
 - Java: 8
 - Bukkit/Spigot: Paper version git-Paper-163 (MC: 1.14.4)
 - dynmap: v3.0-beta-5-218
 - dynmap-structures: v2.2.1

**Additional context**
Dynmap for my server dispaying issue: http://omegacraft.mymc.io:8123

**Comment by omega9380** [comment]
Upon further examination, the coordinate labels are being multiplied by 16 for some reason.  In the screenshot above, the stronghold is at -440,-1416.  -440*16 = -7040, -1416*16 = -22656.

**Comment by KovuTheHusky** [comment]
I will fix this as soon as possible. It's a case of converting from chunk coordinates to block coordinates twice accidentally.

**Comment by KovuTheHusky** [comment]
Closed by 2697fac470ff5a0ffd8cd66716c507acd6ef8ec1.
