### ISSUE TITLE
NullPointerException on new 1.16 server

### ISSUE THREAD

**Issue by kongming819** [KovuTheHusky/dynmap-structures#27]
**Describe the bug**
Server hangs and spills out hundreds of lines about a null pointer exception relating to Dynmap Structures
e.g.:

[WARNING] .... Exception in thread "Thread-479" java.lang.NullPointerException
[WARNING] .... at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:233)
[WARNING] .... at java.lang.Thread.run(Thread.java:813)
[WARNING] .... Exception in thread "Thread-483" java.lang.NullPointerException
[WARNING] .... at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:233)
[WARNING] .... at java.lang.Thread.run(Thread.java:813)
[WARNING] .... Exception in thread "Thread-497" java.lang.NullPointerException
[WARNING] .... at com.kovuthehusky.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:233)
[WARNING] .... at java.lang.Thread.run(Thread.java:813)

**To Reproduce**
Start up server and wait, observing the console

**Expected behavior**
Nothing

**Server:**
 - Java 8 openJ9
 - Paper 1.16.1
 - dynmap 3.1 beta 1
 - dynmap-structures 2.2.1
 - Hosting by server.pro

**Additional context**
For full paste: https://pastebin.com/4xyPRRp6

**Comment by KovuTheHusky** [comment]
Should be fixed in [2.3.0](https://github.com/KovuTheHusky/dynmap-structures/releases/tag/2.3.0). Let me know if you have any issues!

**Comment by kongming819** [comment]
Fantastic, no issues! Thanks, really didn't expect such a quick fix. Kudos
