### ISSUE TITLE
No key position_predicate in MapLike

### ISSUE THREAD

**Issue by Doritoz** [KovuTheHusky/dynmap-structures#28]
The plugin works more is flooding it on the console
I'm using paper paper-68 1.16.1

`[11:00:52 ERROR]: No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:dirt"},output_state:{Name:"minecraft:water",Properties:{level:"0"}},location_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:water"}}]; No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:grass_block"},output_state:{Name:"minecraft:water",Properties:{level:"0"}},location_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:water"}}]; No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:random_block_match",block:"minecraft:grass_path",probability:0.1f},output_state:{Name:"minecraft:grass_block",Properties:{snowy:"false"}},location_predicate:{predicate_type:"minecraft:always_true"}}]; No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:grass_path"},output_state:{Name:"minecraft:oak_planks"},location_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:water"}}]
>.... [11:00:52 ERROR]: No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:dirt"},output_state:{Name:"minecraft:water",Properties:{level:"0"}},location_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:water"}}]; No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:grass_block"},output_state:{Name:"minecraft:water",Properties:{level:"0"}},location_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:water"}}]; No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:random_block_match",block:"minecraft:grass_path",probability:0.1f},output_state:{Name:"minecraft:grass_block",Properties:{snowy:"false"}},location_predicate:{predicate_type:"minecraft:always_true"}}]; No key position_predicate in MapLike[{input_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:grass_path"},output_state:{Name:"minecraft:oak_planks"},location_predicate:{predicate_type:"minecraft:block_match",block:"minecraft:water"}}]`

**Comment by KovuTheHusky** [comment]
What leads you to believe that this is a problem with dynmap-structures?

It appears to be a [bug in Minecraft itself](https://bugs.mojang.com/browse/MC-191388) from a quick search.
