### ISSUE TITLE
config.yml doesn't work

### ISSUE THREAD

**Issue by RuofengX** [KovuTheHusky/dynmap-structures#45]
Release version 2.3.1 in paper1.16.5-777, using Dynmap and nginx + php deploy.
I try to change the config.yml file to set the layer hidden by default, but nothing changed after I restart my game server.
Also, other setting is also invalid in config.yml
Here is my config:
`structures:
  bastionremnant: true
  buriedtreasure: false
  desertpyramid: true
  endcity: true
  fortress: true
  igloo: true
  junglepyramid: true
  mansion: true
  mineshaft: false
  monument: true
  netherfossil: true
  oceanruin: false
  pillageroutpost: false
  ruinedportal: false
  shipwreck: false
  stronghold: true
  swamphut: true
  village: true
layer:
  name: Structures
  hidebydefault: true
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: false`
My website:
[Map](https://oar-01.ruofengx.cn/map)

**Comment by KovuTheHusky** [comment]
From taking a look at the link you provided, it is hidden by default and the structures seem to match. Am I missing something? Please let me know which settings you think are invalid. Thanks!

**Comment by RuofengX** [comment]
Yes, after a full reboot it works.
But you can see [here]( https://oar-01.ruofengx.cn/map/#world;surface;3123,64,-2205;7) this structure is not actually appear in game.
Also, the plugin do a lot of conflict with a chunk generate called Terra. I posted a issue in [Terra project.](https://github.com/PolyhedralDev/Terra/issues/234)
I know it's hard to make the integration with these two, so I just disable dynmap-struct.

**Comment by RuofengX** [comment]
You can check the conflict in [Link](https://oar-01.ruofengx.cn/map/#earth;surface;292,64,250;3), also need to open the structure Layer.

**Comment by KovuTheHusky** [comment]
> Yes, after a full reboot it works.

This is just sort of how things work with most (but not all) plugins.

> But you can see [here](https://oar-01.ruofengx.cn/map/#world;surface;3123,64,-2205;7) this structure is not actually appear in game. (Maybe you need open the structure layer first)

The plugin uses the built-in [locate command](https://minecraft.fandom.com/wiki/Commands/locate) which isn't always entirely accurate. There's not much to do without adding a lot of logic to search the area to see if the structure actually exists.

> Also, the plugin do a lot of conflict with a chunk generate called Terra. I posted a issue in [Terra project.](https://github.com/PolyhedralDev/Terra/issues/234)

I'm not sure what's going on with Terra. Like I said, this plugin only uses the locate command so I assume Terra is putting Village structures all over the place even if it's not generating actual villages in the spot. There doing something odd but I'm sure there's a reason for it. I hope so, at least!

**Comment by RuofengX** [comment]
OK,  I got it. Thanks for reply
