### ISSUE TITLE
Not working on Paper 1.18

### ISSUE THREAD

**Issue by devbaraus** [KovuTheHusky/dynmap-structures#54]
**Describe the bug**
The plugins throws the error when starting the server. 
"[13:13:04 ERROR]: Error occurred while enabling dynmap-structures v2.4.0 (Is it up to date?)
java.lang.NoSuchFieldError: SNOWY_MOUNTAINS"

**To Reproduce**
Add dynmap-structures on plugins folder with dynmap.
Start the server

**Expected behavior**
Start correctly and be enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/43019623/146798864-14427018-f0a8-4185-959f-c59196cd96d9.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Java [17]
 - Paper [git-Paper-59 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)]
 - dynmap [v3.3-beta-3]
 - dynmap-structures [2.4.0]

**Comment by KovuTheHusky** [comment]
Fixed by 4e48728eda85032b25aa97631ce5285406be7cb6. Try updating to [2.5.0](https://github.com/KovuTheHusky/dynmap-structures/releases/tag/2.5.0). Thanks!
