### ISSUE TITLE
Dynmap Spamming the Bastion Remnant Icon everywhere, lagging out slower pc's browsers, and making the map unviewable unless you turn off structures in map.

### ISSUE THREAD

**Issue by Fire8abp** [KovuTheHusky/dynmap-structures#58]
**Describe the bug**
Bastion Remnants are blocking the view of the map.

**To Reproduce**
1. Open Map
2. Map Loads
3. Icons Load
4. Bastion remnants icon spammed 

**Expected behavior**
Icons are where the structures are supposed to be, spread out and accurate to structures location in game.

**Screenshots**
![image](https://user-images.githubusercontent.com/103901009/163729221-7acc923b-48ef-45f4-8670-bd25519c2d78.png)
![image](https://user-images.githubusercontent.com/103901009/163729348-d5de6d03-cc5d-41c0-9a78-7bf125283ef9.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Java 17
 - Paper 1.18.2
 - dynmap 3.4
 - dynmap-structures 2.5.0

**Additional context**
I am running 3 Generation Datapacks, Terralith, Incendium, Nullscape

**Comment by KovuTheHusky** [comment]
The plugin just uses `/locate` and adds a marker for each result. I would recommend disabling Bastion Remnants in `config.yml`. I will look into if I can coalesce results or something.

**Comment by Fire8abp** [comment]
Ok, thank you, it seems it was a problem with that specific dynmap world folder, i renamed that world and it seems that fixed the issue as it created a new folder for it.
